# Generated by Django 6.0.3 on 2026-03-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clause',
            name='page_number',
        ),
        migrations.AddField(
            model_name='clause',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clause',
            name='start_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clause',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='clause',
            name='confidence_score',
            field=models.FloatField(default=1.0),
        ),
    ]
